
FROM python:3.12
LABEL maintainer="aamirazhar327@gmail.com"
WORKDIR /code
RUN pip install poetry
COPY . /code/
RUN poetry config virtualenvs.create false
RUN poetry install
EXPOSE 8000
CMD ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload"]